version: '3'
services:
  metabase:
    image: metabase/metabase
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - "./metabase-data:/metabase-data"
    ports:
      - 3000:3000
